import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  map: {
    width: '100%',
    height: '100%',
  },
  centerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
    padding: 20,
  },
  loadingText: {
    marginTop: 16,
    fontSize: 14,
    color: '#666',
  },
  errorText: {
    fontSize: 14,
    color: '#d32f2f',
    textAlign: 'center',
  },
menuButton: {
  position: 'absolute',
  top: 50,
  left: 16,
  width: 48,
  height: 48,
  borderRadius: 24,
  backgroundColor: '#fff',
  zIndex: 10,    // ← YENİ
  justifyContent: 'center',
  alignItems: 'center',
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.15,
  shadowRadius: 4,
  elevation: 4,
},
  menuIcon: {
    fontSize: 22,
    color: '#1e3a5f',
  },
countBadge: {
  position: 'absolute',
  top: 110,         
  right: 16,
  paddingHorizontal: 14,
  paddingVertical: 8,
  borderRadius: 16,
  backgroundColor: '#fff',
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.15,
  shadowRadius: 4,
  elevation: 4,
},
  countText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#1e3a5f',
  },
  tripButton: {
  position: 'absolute',
  bottom: 30,
  right: 16,
  width: 56,
  height: 56,
  borderRadius: 28,
  backgroundColor: '#1e3a5f',
  justifyContent: 'center',
  alignItems: 'center',
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.2,
  shadowRadius: 4,
  elevation: 6,
},
tripIcon: {
  fontSize: 26,
},
});