import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  map: {
    width: '100%',
    height: '100%',
  },
  centerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
    padding: 20,
  },
  loadingText: {
    marginTop: 16,
    fontSize: 14,
    color: '#666',
  },
  errorText: {
    fontSize: 14,
    color: '#d32f2f',
    textAlign: 'center',
  },
menuButton: {
  position: 'absolute',
  top: 50,
  left: 16,
  width: 48,
  height: 48,
  borderRadius: 24,
  backgroundColor: '#fff',
  zIndex: 10,    // ← YENİ
  justifyContent: 'center',
  alignItems: 'center',
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.15,
  shadowRadius: 4,
  elevation: 4,
},
  menuIcon: {
    fontSize: 22,
    color: '#1e3a5f',
  },
countBadge: {
  position: 'absolute',
  top: 110,         
  right: 16,
  paddingHorizontal: 14,
  paddingVertical: 8,
  borderRadius: 16,
  backgroundColor: '#fff',
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.15,
  shadowRadius: 4,
  elevation: 4,
},
  countText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#1e3a5f',
  },
  tripButton: {
  position: 'absolute',
  bottom: 30,
  right: 16,
  width: 56,
  height: 56,
  borderRadius: 28,
  backgroundColor: '#1e3a5f',
  justifyContent: 'center',
  alignItems: 'center',
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.2,
  shadowRadius: 4,
  elevation: 6,
},
tripIcon: {
  fontSize: 26,
},
stateButton: {
  position: 'absolute',
  top: 160,
  right: 16,
  flexDirection: 'row',
  alignItems: 'center',
  backgroundColor: '#fff',
  paddingHorizontal: 12,
  paddingVertical: 8,
  borderRadius: 16,
  zIndex: 10,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.15,
  shadowRadius: 4,
  elevation: 4,
},
stateIcon: {
  fontSize: 14,
  marginRight: 6,
},
stateText: {
  fontSize: 12,
  fontWeight: '600',
  color: '#1e3a5f',
},
stateModalOverlay: {
  flex: 1,
  backgroundColor: 'rgba(0,0,0,0.5)',
  justifyContent: 'flex-end',
},
stateModalContent: {
  backgroundColor: '#fff',
  borderTopLeftRadius: 24,
  borderTopRightRadius: 24,
  maxHeight: '75%',
  paddingBottom: 30,
},
stateModalHeader: {
  paddingHorizontal: 20,
  paddingTop: 20,
  paddingBottom: 16,
  borderBottomWidth: 1,
  borderBottomColor: '#eee',
},
stateModalTitle: {
  fontSize: 18,
  fontWeight: '700',
  color: '#1e3a5f',
  marginBottom: 4,
},
stateModalSubtitle: {
  fontSize: 12,
  color: '#666',
},
clearTrailsButton: {
  marginHorizontal: 20,
  marginVertical: 12,
  paddingVertical: 10,
  backgroundColor: '#fee',
  borderRadius: 8,
  alignItems: 'center',
},
clearTrailsText: {
  fontSize: 13,
  fontWeight: '600',
  color: '#d32f2f',
},
stateItem: {
  flexDirection: 'row',
  alignItems: 'center',
  paddingVertical: 14,
  paddingHorizontal: 20,
  borderBottomWidth: 1,
  borderBottomColor: '#f5f5f5',
},
stateItemActive: {
  backgroundColor: '#e8f5e9',
},
stateItemCode: {
  fontSize: 14,
  fontWeight: '700',
  color: '#1e3a5f',
  width: 40,
},
stateItemName: {
  flex: 1,
  fontSize: 14,
  color: '#333',
},
stateItemCheck: {
  fontSize: 18,
  color: '#2e7d32',
  fontWeight: '700',
},
cityButton: {
  position: 'absolute',
  top: 215,
  right: 16,
  flexDirection: 'row',
  alignItems: 'center',
  backgroundColor: '#fff',
  paddingHorizontal: 12,
  paddingVertical: 8,
  borderRadius: 16,
  zIndex: 10,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.15,
  shadowRadius: 4,
  elevation: 4,
},
cityIcon: {
  fontSize: 14,
  marginRight: 6,
},
cityText: {
  fontSize: 12,
  fontWeight: '600',
  color: '#1e3a5f',
},
});