import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.3)',
  },
  sheet: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingBottom: 30,
    maxHeight: '85%',
    minHeight: '50%',
  },
  handle: {
    width: 60,
    height: 4,
    backgroundColor: '#ddd',
    borderRadius: 2,
    alignSelf: 'center',
    marginTop: 10,
    marginBottom: 16,
  },
  stickyHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingHorizontal: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  headerContent: {
    flex: 1,
  },
  parkName: {
    fontSize: 22,
    fontWeight: '600',
    color: '#1e3a5f',
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 13,
    color: '#666',
  },
  closeButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#f0f0f0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeText: {
    fontSize: 16,
    color: '#666',
  },
  scrollContent: {
    paddingTop: 16,
  },
  buttonRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 20,
    paddingHorizontal: 20,
  },
  primaryButton: {
    flex: 1,
    backgroundColor: '#1e3a5f',
    paddingVertical: 12,
    borderRadius: 20,
    alignItems: 'center',
  },
  primaryButtonText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '500',
  },
  secondaryButton: {
    flex: 1,
    backgroundColor: '#f0f0f0',
    paddingVertical: 12,
    borderRadius: 20,
    alignItems: 'center',
  },
  secondaryButtonText: {
    color: '#333',
    fontSize: 13,
    fontWeight: '500',
  },
  section: {
    marginBottom: 20,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#eee',
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1e3a5f',
    marginBottom: 12,
    paddingHorizontal: 20,
  },
  videoList: {
    paddingHorizontal: 20,
  },
  info: {
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#eee',
    paddingHorizontal: 20,
  },
  infoTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1e3a5f',
    marginBottom: 4,
  },
  infoText: {
    fontSize: 13,
    color: '#666',
  },
  addedButton: {
  backgroundColor: '#e8f5e9',
},
addedButtonText: {
  color: '#2e7d32',
},
tripBadge: {
  marginHorizontal: 20,
  marginBottom: 12,
  paddingVertical: 8,
  paddingHorizontal: 12,
  backgroundColor: '#e8f5e9',
  borderRadius: 8,
  alignSelf: 'flex-start',
},
tripBadgeText: {
  fontSize: 12,
  color: '#666',
},
tripBadgeName: {
  fontWeight: '700',
  color: '#2e7d32',
},
trailInfoCard: {
  backgroundColor: '#f8f9fa',
  marginHorizontal: 20,
  padding: 16,
  borderRadius: 12,
  borderWidth: 1,
  borderColor: '#e8f5e9',
},
trailInfoRow: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  paddingVertical: 8,
  borderBottomWidth: 1,
  borderBottomColor: '#eee',
},
trailInfoLabel: {
  fontSize: 13,
  color: '#666',
  fontWeight: '500',
},
trailInfoValue: {
  fontSize: 13,
  color: '#1e3a5f',
  fontWeight: '600',
},
trailYes: {
  color: '#2e7d32',
},
trailNo: {
  color: '#999',
},
trailDescription: {
  fontSize: 13,
  color: '#555',
  paddingHorizontal: 20,
  lineHeight: 20,
},
trailUnknown: {
  color: '#999',
  fontStyle: 'italic',
},
alternateName: {
  fontSize: 11,
  color: '#999',
  fontStyle: 'italic',
  marginTop: 2,
},
infoCard: {
  marginHorizontal: 20,
  marginVertical: 16,
  paddingVertical: 8,
  paddingHorizontal: 14,
  backgroundColor: '#f8f9fa',
  borderRadius: 12,
  borderWidth: 1,
  borderColor: '#e0e0e0',
},
infoRow: {
  flexDirection: 'row',
  alignItems: 'center',
  paddingVertical: 8,
},
infoIcon: {
  fontSize: 16,
  marginRight: 10,
  width: 22,
},
infoText: {
  flex: 1,
  fontSize: 13,
  color: '#333',
  lineHeight: 18,
},
openText: {
  color: '#2e7d32',
  fontWeight: '600',
},
closedText: {
  color: '#d32f2f',
  fontWeight: '600',
},
websiteText: {
  color: '#1976d2',
  fontWeight: '600',
  textDecorationLine: 'underline',
},
reviewsContainer: {
  paddingHorizontal: 20,
},
reviewCard: {
  backgroundColor: '#fafafa',
  padding: 14,
  borderRadius: 10,
  marginBottom: 10,
  borderLeftWidth: 3,
  borderLeftColor: '#1e3a5f',
},
reviewHeader: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
  marginBottom: 8,
},
reviewAuthor: {
  fontSize: 13,
  fontWeight: '700',
  color: '#1e3a5f',
  flex: 1,
},
reviewMeta: {
  alignItems: 'flex-end',
},
reviewStars: {
  fontSize: 11,
  marginBottom: 2,
},
reviewTime: {
  fontSize: 10,
  color: '#999',
},
reviewText: {
  fontSize: 12,
  color: '#444',
  lineHeight: 18,
},
distanceText: {
  fontSize: 12,
  color: '#1976d2',
  marginTop: 2,
  fontWeight: '600',
},
favoriteButton: {
  marginHorizontal: 20,
  marginTop: 8,
  paddingVertical: 12,
  borderRadius: 12,
  backgroundColor: '#fff',
  borderWidth: 1.5,
  borderColor: '#e91e63',
  alignItems: 'center',
},
favoriteButtonActive: {
  backgroundColor: '#fce4ec',
  borderColor: '#c2185b',
},
favoriteButtonText: {
  fontSize: 13,
  fontWeight: '600',
  color: '#e91e63',
},
favoriteButtonTextActive: {
  color: '#c2185b',
},
weatherContainer: {
  paddingHorizontal: 20,
},
weatherList: {
  paddingRight: 20,
},
weatherCard: {
  backgroundColor: '#f8f9fa',
  borderRadius: 12,
  paddingVertical: 12,
  paddingHorizontal: 10,
  marginRight: 8,
  alignItems: 'center',
  minWidth: 80,
  borderWidth: 1,
  borderColor: '#e0e0e0',
},
weatherDay: {
  fontSize: 11,
  fontWeight: '700',
  color: '#1e3a5f',
  marginBottom: 4,
},
weatherIcon: {
  width: 50,
  height: 50,
  marginVertical: 2,
},
weatherTemp: {
  fontSize: 16,
  fontWeight: '700',
  color: '#1e3a5f',
},
weatherTempMin: {
  fontSize: 12,
  color: '#999',
  marginBottom: 4,
},
weatherCondition: {
  fontSize: 10,
  color: '#666',
  textAlign: 'center',
},
});